### ISSUE TITLE
Several outputs

### ISSUE THREAD

**Issue by somenxavier** [thanethomson/statik#39]
Is there possible to define several outputs from a file? I plan to generate a beamer file from markdown one using pandoc. Is it possible? How?

**Comment by thanethomson** [comment]
Please explain your use case in more detail? Are you trying to run Statik and Pandoc simultaneously? (i.e. running Statik on your sources, while chaining Pandoc to run on your Markdown files?)

**Comment by somenxavier** [comment]
Just that a markdown file generate an html, a beamer file, whatever I like using more than statik built-in markdown-to-html conversion. I want to be able to generate a desired output with desired tool.

**Comment by thanethomson** [comment]
Just to clarify then, are you looking for some kind of higher-level build tool that will allow you to run a whole bunch of tools on your project in a specific sequence? e.g.

1. Run Pandoc on your Markdown files to generate Beamer presentations.
2. Run Statik on your Markdown files to generate HTML.
3. Run wkhtmltojpeg to generate JPEG snapshots.

Like that? If so, Statik unfortunately doesn't support such complex builds. It's single-purpose only at the moment, and I think that, perhaps, rather using tools like [gulp.js](http://gulpjs.com/) may be better for you, because then you could use a single tool to manage your JavaScript/CSS dependencies, cross-language compiling, Statik execution, execution of other tools, etc.

**Comment by thanethomson** [comment]
Closing issue for now. If you still want to discuss this, please reopen the issue.
