### ISSUE TITLE
Generating files with no extension (.htaccess)

### ISSUE THREAD

**Issue by zejott** [thanethomson/statik#40]
Hi, 

I was trying to automatically place a .htaccess-file in my generated website. It works for sitemap.xml and robots.txt, but without an extension, statik creates a .htaccess/index.html. 

I would work on a pull request, but first I want to know if I am missing something or if there is any other way to solve this.

**Comment by thanethomson** [comment]
You're right - Statik wouldn't allow for the creation of files without a filename, and the code that causes this is around these two locations:

* [views.py line 137](https://github.com/thanethomson/statik/blob/v0.16.1/statik/views.py#L137)
* [views.py line 164](https://github.com/thanethomson/statik/blob/v0.16.1/statik/views.py#L164)

If you've got some time to look into adding a fix and some unit tests to check the fix, the help would be greatly appreciated 😀 Otherwise I may be able to get to this in the next week or two.

**Comment by pztrick** [comment]
@thanethomson @zejott I just made a pull request.

There is a semantic question about whether `.htaccess` is itself an extension or the name... but seemed cleaner to handle this special case in `utils.get_url_file_ext` rather than handling it duplicatively in both `process_simple()` and `process_complex()`.

**Comment by thanethomson** [comment]
Should be fixed in `v0.16.2`, now released.
