### ISSUE TITLE
Enable quiet output for Statik

### ISSUE THREAD

**Issue by tombreit** [thanethomson/statik#45]
I'm generating a Statik project via `.gitlab-ci.yml`, but I got (gitlab-) errors because

```
Writing output fi
[31;1mJob's log exceeded limit of 4194304 bytes.[0;m
```
This project has do deal with a lot of (generated)  pages (from `data/Photos/_all.yml`): 
```
public$ find . -type  f  |wc -l
56350
```
... and perhaps my gitlab runner would not fail when I could run Statik in a quiet mode (which only outputs errors), like `statik --quiet`. 
Or I write a wrapper script which suppresses the output...

**Comment by thanethomson** [comment]
Good idea - this should be a quick feature to build in.

**Comment by thanethomson** [comment]
Now enabled in `v0.17.0`. I've also relegated the file listing to the `DEBUG` logging level (for when one explicitly asks for verbose logging) instead of the `INFO` level. Simply do the following to enable quiet mode (which only outputs errors or exceptions):

```bash
> statik --quiet
```

To run Statik completely silently (no exception/error logging), do the following:

```bash
> statik --quiet --fail-silently
```
