### ISSUE TITLE
built-in SFTP upload

### ISSUE THREAD

**Issue by konstruktiv** [thanethomson/statik#61]
@thanethomson You mentioned built-in SFTP upload in #35 and I also think it would be a cool feature to add. Do you have any plans to implement it?

**Comment by thanethomson** [comment]
Yeah, this would be great. I've marked it as an enhancement here if anyone wants to implement it before I get around to it. Probably a good few hours' worth of work, unless there's a Python library that implements all of the necessary functionality out of the box.

Basically, the way I'd see it working is as follows:

1. It should support both FTP(S) and SFTP.
2. The connection parameters should either be specified in your `config.yml` file or on the command line. SSH keys should be supported, optionally prompting for a password from `stdin`.
3. It should only perform the file transfer when (1) the project compiles successfully and (2) you're not watching for changes (otherwise it'll just keep uploading on every change, which will slow down the watching process significantly).
4. It should only upload modified files to keep the upload time to a minimum (kinda like `rsync` functionality).

I've been thinking about building a CMS application for Statik for some time now, which would probably be a more appropriate place for this functionality. The ideal would be some kind of desktop application with Statik built-in (probably using [Thrust](https://github.com/breach/thrust/)), where the web component of the IDE could easily be hosted as a web application on your own server in addition to the desktop app (like Slack), or perhaps a specialised plugin with support for one or two of the major IDEs (like PyCharm/Eclipse/etc.).

**Comment by konstruktiv** [comment]
Great ideas. A CMS interface would be a nice fit for Statik, it would take some effort though.

On your other points:

1. FTP(S) and SFTP are completely different protocols. AFAIK implementing both would require the use of two separate libraries. For SFTP there is [Paramiko](http://www.paramiko.org) or [pysftp](https://pypi.python.org/pypi/pysftp) which requires Paramiko.
2. How about starting with SSH passwords and implementing keys later?
3. How do we know that the project compiles successfully? Is there a log somewhere?
4. Does Statik keep track of modified files?

Would you prefer if all points were implemented at once, or prioritize and go step by step?

**Comment by thanethomson** [comment]
Yup:

1. I'd say SFTP would be first priority, and then FTP(S) later (I'd consider them legacy technologies, but some people are forced to use them for various reasons).
2. Implementing SSH keys and passwords as features are both pretty easy to implement.
3. Yes - Statik throws an exception if something goes wrong.
4. No - this is probably going to be the biggest challenge. Might be a good idea to implement this later once the overall SFTP functionality is working.

**Comment by konstruktiv** [comment]
I submitted a pull request for adding basic SFTP upload functionality: #73

**Comment by jayvdb** [comment]
@konstruktiv , this is already completed and can be closed?

**Comment by konstruktiv** [comment]
Built-in SFTP implementation with added key support: https://github.com/thanethomson/statik/commit/e0f0c5f51ad678c0c214da501f790aec66351e09
