### ISSUE TITLE
how-to: represent a list as an attribute in yml data instance

### ISSUE THREAD

**Issue by minskmaz** [thanethomson/statik#62]
It's a useful pattern but I didn't see anything about it in the docs and I get errors when I try to represent a list as an attribute in a model.

**Comment by thanethomson** [comment]
Statik uses SQLite under the hood to model data, whose [supported data types](http://www.sqlite.org/datatype3.html) don't include arrays. This means that Statik would have to manually serialize/deserialize lists of items from the in-memory database (probably from a TEXT field). This poses problems, like an inability to search through this data easily, type detection, and choosing a serialization approach (e.g. pickling).

What types of lists would you like to represent? Simple ones, like strings or numbers? Or complex ones, like lists of objects?

**Comment by minskmaz** [comment]
I've come up with a workaround wherein I:

1. provide a template name as an attribute of the model
2. stamp that out into an jinja include statement
3. make a model to define the list object and an _all.yml for its elements
4. add the list by name to a dynamic query in the view
5. loop through the elements in template I dynamically referenced

**Comment by thanethomson** [comment]
Sounds like an interesting workaround! Do you perhaps have some snippets of what that looks like?

Perhaps there's a use case there that warrants generalisation - if there is, then it's definitely grounds for coming up with an enhancement to Statik.

**Comment by minskmaz** [comment]
Thane - thanks for your response. I'm trying to avoid this kind of syntax as I don't want to have to make a model & instance for every last list entry. If I'm missing something please let me know.

https://gist.github.com/minskmaz/b73248e56e9b6292561474444f536b6a

**Comment by thanethomson** [comment]
Ah I see. In this particular case, wouldn't it perhaps work better to make your `subtitle` field be of type `Content` and then put Markdown content into your file? Like so:

Your model:

```yml
title: String
subtitle: Content
```

`_all.yml`:
```yml
- pk: some-pk
  title: Here's the title
  subtitle: |
    Here's some Markdown content, with a list:
    * Point 1
    * Point 2
```

This way, at least in theory, Statik should convert that `subtitle` string into HTML for you.

**Comment by minskmaz** [comment]
Thane, great idea and thank for heads up - is there a way to match css classes to Markdown elements ?? I looked through the docs but nothing popped out at me.

**Comment by thanethomson** [comment]
No, unfortunately not. The easiest way to do so is by way of your template and restructuring your CSS a little. Something like:

```html+jinja
<div class="instances">
  {% for item in instances %}
    <div class="instance">
      <div class="title">{{ instance.title }}</div>
      <div class="subtitle">{{ instance.subtitle|safe }}</div>
    </div>
  {% endfor %}
</div>
```

The `safe` filter is important when injecting the `subtitle` field to tell Jinja not to escape all the HTML characters.

And then alter your CSS like so:

```css
div.instances div.subtitle li {
  // your list item properties here
}
```

**Comment by jayvdb** [comment]
I would also like the originally proposed feature.

In a data dense site, having to create all of the models is tiresome and unnecessarily complicated.

To use the "tags" example, it should be possible to do:

Post.yml
```yaml
title: String
tags: String[]
body: Content
```
instance
```yaml
title: Foo
tags:
  - bar
  - baz
```

The model above using `String[]` is accepted by statik, but then everything falls apart when the data intance is being rendered.

I would further propose that this is implemented as an implicit "unnamed" model, which would probably be named something like `_post_tags` under the covers, so it could be queried if desired, but typically it would be used when querying isnt needed.

In the case of tags, the above isnt ideal, because this implicit model cant have reverse relationships that are recognised within statik.  But there are many times that a very simple list is needed in the output, and there is no need for reverse mappings or query-ability.

My use case is migrating https://github.com/coala/coala/tree/master/coalib/bearlib/languages/definitions into a separate metadata only yaml repo with a site generator attached to make it easier for the data to be browsed, additions (especially relationships) to be checked 'visually', etc.  We would then periodically import the yaml into python.  Related to https://github.com/coala/coala/issues/3166 , https://github.com/coala/coala/issues/4261 and https://github.com/coala/coala/issues/4038
